version: '3.9'

services:
  app:
    build: .
    container_name: fastapi-ml-app
    ports:
      - "8000:8000"
    networks:
      - ml-network
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis-db
    ports:
      - "6379:6379"
    networks:
      - ml-network

networks:
  ml-network:
    driver: bridge
